### ISSUE TITLE
Bug: Option per page doesn't work in responsive case

### ISSUE THREAD

**Issue by mercs600** [SSENSE/vue-carousel#116]
I took responsive example from documentation page. When slides content have various width then "option per page" is not respected. 

You can see this behavior on jsfiddle below. I added to first slide div with 300px width. On smaller resolutions we should get 4 slides in row, but first slide is pushing... 
https://jsfiddle.net/mv17mxsp/

**Comment by quinnlangille** [comment]
Hey @mercs600, just took a look at your fiddle. You've got `perPageCustom` configured to 2 and 3 slides, which is overriding your `perPage: 4` (I've just made a PR ( #125 ) to clarify this interaction in the documentation). 

However, your problem comes from setting a hard width on your elements - two 300px elements can't fit on a 480px screen. I'm not sure what you're trying to achieve with your design, but you could try adding `max-width: 100%` -> you can see an example of that working [here](https://jsfiddle.net/quinnssense/1uk73fmq/1/) (the carousel itself would need some styling as well, but it should get the point across)

**Comment by quinnlangille** [comment]
Haven't heard back here so will close this, feel free to open a new issue if there are still any problems :~)
