### ISSUE TITLE
Bug: VueCarousel-wrapper class is lost after 0.6.7 update

### ISSUE THREAD

**Issue by lennoximus** [SSENSE/vue-carousel#130]
Evening. 
After 0.6.7 update you've introduced carousel wrapper ref but also removed its class from Carousel.vue component which results in all slides showing at the same time without wrapper's 'overflow: hidden' css property.
I've tried to create pull request with this feature returned, however I ended up with some problems related to jest tests, so we have what we have.

**Comment by quinnlangille** [comment]
Hey @lennoximus, thanks for pointing that out! Was your PR just blocked because of the coveralls check? If you don't mind, can you make the PR and I'll deal with the coveralls check!

**Comment by lennoximus** [comment]
PR was blocked due to client tests, @quinnlangille. While running these tests I'm facing to tests not passing only because of whitespaces mismatch in components' snapshots. PR #133 is all good though, kind of.

**Comment by quinnlangille** [comment]
Yeah just saw that - commented on the PR with instructions, there's a command that will automatically update the snapshots. It's just because we updated the snapshots after we deleted the class, so we'll need to re-add them! Let me know if you have any issues. Also, you can run `npm run test` in your console to check locally before you push. Thanks! :~)

**Comment by quinnlangille** [comment]
Merged! Going to close this now, thanks so much for contributing :~)
