### ISSUE TITLE
Question: Is it possible to block the touch/mouse from moving slider

### ISSUE THREAD

**Issue by NickMcBurney** [SSENSE/vue-carousel#181]
Hi,

Im trying to build an application which requires a carousel but I only want to change the active slide using the getNextPage() & getPreviousPage() methods.

I have added 'mouseDrag' and set to false `:mouseDrag="false"` and also `:minSwipeDistance="999999999"` but I can still change slides using touch.

Im wondering if it is possible to completely block the users ability to change slide without the methods mentioned above?

Thanks
Nick

**Comment by quinnlangille** [comment]
Hey @NickMcBurney, the carousel checks if `this.mouseDrag` is enabled, OR if the window has an `ontouchstart` event to enable dragging. The ontouchstart event's differ between browsers, but if you remove the listener then your dragging should not work.

Otherwise, I'll switch this to a bug report as that should be the intended functionality

**Comment by NickMcBurney** [comment]
@quinnlangille I've tried removing the check within /node_modules/vue-carousel/dist/vue-carousel.min.js - by removing `this.isTouch||` shown in screenshot below:
![image](https://user-images.githubusercontent.com/6604187/41354026-d866c51e-6f15-11e8-815e-c1212b560920.png)

This seems to work on my Android phone (Essential PH-1) but not on iPhone 6

There is a pull request for adding the functionality: #91 - would be great to get this added as functionality rather than this fix.

**Comment by quinnlangille** [comment]
Hmm yeah I can look at refreshing that PR, is really out of date but could be worth looking into. I'll check it out later this week!

**Comment by OnnoGeorg** [comment]
Has this been solved? I am trying the block any slide change by swipe on mobile devices, but can not figure out how to achieve this.

A solution by adding `pointer-events: none` to the stylesheet is not possible, because I need those pointer events in the slides (they contain some active elements).

So, any option like `swipeEnable` would be highly appreciated!

**Comment by NickMcBurney** [comment]
@quinnlangille I've created a new pull request for this: https://github.com/SSENSE/vue-carousel/pull/296

**Comment by quinnlangille** [comment]
Hey @NickMcBurney, thanks! I'll take a look at it now :octocat:
