### ISSUE TITLE
Bug: pagination dots count error

### ISSUE THREAD

**Issue by ishowshao** [SSENSE/vue-carousel#20]
just this simple example:  i got four dots, it's ok if i use `template` in Vue constructor

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="../dep/vue.js"></script>
    <script src="../dep/vue-carousel.min.js"></script>
</head>
<body>
<div id="example">
    <carousel :perPage="1">
        <slide>1</slide>
        <slide>2</slide>
        <slide>3</slide>
    </carousel>
</div>
<script>
    new Vue({
        el: '#example',
        components: {
            'carousel': VueCarousel.Carousel,
            'slide': VueCarousel.Slide
        },
    });
</script>
</body>
</html>
```

**Comment by toddlawton** [comment]
I hadn't previously used Vue in this way before. I worked on an example locally similar to your implementation and I noticed the behaviour is definitely different. The carousel relies on `$slots.default` being used for slide content only. When using the template syntax, the slides are passed into that array and the extra components such as navigation and pagination are in `$children` as they should be. I saw that with your example syntax, they are all merged into the `$slots.default` array. Due to that, with 3 slides the carousel will think there's an extra page (which is actually the pagination component) and will show 4 pages. 

Another oddity in the above syntax is that props appear to be lowercased/ignored. For example in my template I wrote:
``` html
<carousel :perPage="3">
```

which rendered out to:
``` html
<div class="VueCarousel" perpage="3">
```
In the Vue devtools I observed that the `perPage` prop was not actually passed in.

For those reasons I'd strongly suggest using a template in your app. I could add a `.filter` on the slots array to include only `slide` tags but I'd prefer not to degrade the performance for this use case.
