### ISSUE TITLE
Is it possible to hide/disable the navigation when only 1 slide is present?

### ISSUE THREAD

**Issue by xJREB** [SSENSE/vue-carousel#208]
When only one slide is present in the carousel, no navigation is possible, yet the navigation/pagination is still displayed which is a bit confusing for the user. Is there currently a possibility to hide/disable it in this case? Great component btw, really like it. 👍

**Comment by quinnlangille** [comment]
It sure is! You can pass `:paginationEnabled=false` to turn off the dots

**Comment by xJREB** [comment]
Thanks! For anyone wondering how I used this:

```html
<carousel :per-page="1" :navigation-enabled="array.length > 1" :pagination-enabled="array.length > 1">
    <slide v-for="item in array" v-bind:key="item.id">
        {{item.text}}
    </slide>
</carousel>
```

**Comment by rafeeque-cairs** [comment]
@xJREB, It won't work. Because we'll have more than 1 item in the array even in the smaller width screens. So better we can check if the window width is greater than the mobile width.

`<carousel :perPageCustom="[[0, 1], [438, 2], [768, 3], [992, 4]]" :paginationEnabled="window.innerWidth >= 437" :navigationEnabled="window.innerWidth < 437" :loop="window.innerWidth < 437" :autoplayTimeout="3000">
    <slide v-for="(item, i) in array" :key="i" :data-index="i">
        
    </slide>
</carousel>`
