### ISSUE TITLE
Any way to move the pagination onto the Carousel?

### ISSUE THREAD

**Issue by GummyVites** [SSENSE/vue-carousel#239]
looking through the docs I couldn't find anything for this.

 Tried:
`  .VueCarousel-pagination{
    position: absolute;
    margin-bottom: 20px;
  }`

**Comment by quinnlangille** [comment]
Hey @GummyVites, we don't have a native way to do this but it should definitely be possible with CSS, either by adding a class to the carousel as mentioned in #14, or by hijacking a class like you've attempted. 

I'd guess that it's not working due to a scope issue, maybe try adding an `!important` flag, or being more specific with your selector

**Comment by quinnlangille** [comment]
Since I havne't heard back on this one will close it up. Feel free to reopen or open a new issue if you still have any questions :octocat:

**Comment by boctulus** [comment]
Is possible to make it works? I've tried :paginationPosition="bottom-overlay" but I got this:

Property or method "bottom" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property
