### ISSUE TITLE
In mobile, click on image of carousel, it pops up and allow zoom.

### ISSUE THREAD

**Issue by kenpeter** [SSENSE/vue-carousel#407]
I want to do something similar like [this](https://www.revolveclothing.com.au/mobile/one-teaspoon-bandits-high-waist-short/dp/ONET-WF67/?&d=Womens&page=1&lc=1&itrownum=1&itcurrpage=1&itview=01&product=ONET-WF67)

If I go to mobile size, click on the image
1. It pops up
2. Able to scroll in popup
3. Able to zoom in popup

What is the best place in the code to implement these?

**Comment by quinnlangille** [comment]
Hey @kenpeter, the carousel emits events on click (not currently on hover, but it could be easily implemented). The "pop-up" you're describing would need to be built outside of the carousel - we don't have or plan on having anything like that natively. Will close this now, since it's not related to the carousel - feel free to open another issue or comment here if anything else comes up!
