### ISSUE TITLE
How to add Fontawsome Icons for Nav Arrows?

### ISSUE THREAD

**Issue by theomanus** [SSENSE/vue-carousel#453]
Hi guys,

Im new to vuejs and in my first project Im using fontawsome icons, which i would like to integrate into your carousel.
I saw that its possible to add a String for next and prev, but dont know how really to add the cheatsheet of the fontawsome icons so that it really works.
Can you help me out with that?

**Comment by irongollem** [comment]
I don't think you can. You could try and muck around with the font position and setting the font of the entire component to your font but ideally the author (or a PR) makes the navigation buttons available through a slot (besides the prop). Which can then hold whatever.

**Comment by quinnlangille** [comment]
@irongollem is correct, we currently don't support fully custom components as navigation (a.k.a passing a FE `<i>` tag as the navigation) but using slots would solve this issue.

@theomanus if you engineer a solution on your end, feel free to open a PR!
Will close this for now, since we don't have an official solution. Feel free to make a feature request using the proper template if you'd like us or someone else to work on it!

**Comment by Qvatra** [comment]
just found that that actually could be done. see https://github.com/SSENSE/vue-carousel/issues/21
would be nice to add this in docs
