### ISSUE TITLE
navigationNextLabel usage

### ISSUE THREAD

**Issue by craigwillis85** [SSENSE/vue-carousel#50]
Hi

Not sure I'm using the  `navigationNextLabel` correctly, but the code below, gives me an error:

`Property or method "Next" is not defined on the instance but referenced during render.`

    <carousel :perPage="1" :navigationEnabled="false" :navigationNextLabel="Next">
        <slide>
            Slide 1 Content
        </slide>
        <slide>
            Slide 2 Content
        </slide>
    </carousel>

**Comment by UXandre** [comment]
The first thing is that you should use kebab-case equivalents when using in-DOM templates as HTML attributes are case-insensitive. 

`<carousel :per-page=1 :navigation-enabled=false>
    <slide>
        Slide 1 Content
    </slide>
    <slide>
        Slide 2 Content
    </slide>
</carousel>`

This works with all the props with a type either of boolean or number. However, for other data types like string and array, it doesn't work for me, either. 

When I put 
`<carousel :pagination-active-color="#9966cc">`

I got error:
[Vue warn]: Error compiling template:
- invalid expression: :pagination-active-color="#9966cc"
 
(found in <Root>)

Would really appreciate it if anyone can help.

**Comment by toddlawton** [comment]
Unfortunately we won't be supporting in-DOM templates with this plugin. @craigwillis85 the error you're specifically encountering is caused by your use of the colon in front of navigationNextLabel. When you use a colon, vue will parse the contents in double quotes as if it were literal javascript. Vue will look for a variable called Next with doesn't exist and trip out.

**Comment by craigwillis85** [comment]
@toddlawton yeah I noticed this, but forgot to update the issue
