### ISSUE TITLE
Change background styles on pagination

### ISSUE THREAD

**Issue by iamdubx** [SSENSE/vue-carousel#94]
Is it possible to add ability to change not only the color and padding, but set background image on dots?

**Comment by quinnlangille** [comment]
Hey @iamdubx, you can add custom css and style the buttons that way ( see issue #14 ). Otherwise, if you'd like to see something work on the component level through a prop, feel free to submit a PR! Make sure to check our [contributor guidelines](https://github.com/SSENSE/vue-carousel/blob/master/CONTRIBUTING.md) for our commit/branch naming conventions.
